sudo: required
services:
    - docker

before_install:
    - docker build -t ysandee/react-project -f Dockerfile_dev .

script:
    - docker run -e CI=true ysandee/react-project npm run test

deploy:
    - provider: elasticbeanstalk
      region: us-west-1 # Specify your region
      app: "react-project-docker-staging" # Copy it from Elastic Beanstalk dashboard
      env: "ReactProjectDockerStaging-env" # Copy it from Elastic Beanstalk dashboard
      bucket_name: "elasticbeanstalk-us-west-1-333442415632"
      bucket_path: "docker"
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key: $AWS_SECRET_KEY
      on:    
         branch: staging 
    - provider: elasticbeanstalk
      region: us-west-1 # Specify your region
      app: "react-project-docker" # Copy it from Elastic Beanstalk dashboard
      env: "ReactProjectDocker-env-new" # Copy it from Elastic Beanstalk dashboard
      bucket_name: "elasticbeanstalk-us-west-1-333442415632"
      bucket_path: "docker"
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key: $AWS_SECRET_KEY
      on:    
         branch: master
